version: "3.9"
services:
  frontend:
    restart: always
    image: task-management-ui:latest
    hostname: task-management-ui
    container_name: task-management-ui
    networks:
      - external-net
#    image: task-management-ui:latest
#    container_name: task-management-ui
#    hostname: task-management-ui
#    ports:
#      - "3003:80"
networks:
  external-net:
    name: external-net
    external: true